#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanweb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VzWebfinalvers")]
	public partial class dbSanPhamDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcart(cart instance);
    partial void Updatecart(cart instance);
    partial void Deletecart(cart instance);
    partial void InsertCHUC_VU(CHUC_VU instance);
    partial void UpdateCHUC_VU(CHUC_VU instance);
    partial void DeleteCHUC_VU(CHUC_VU instance);
    partial void InsertCT_HD(CT_HD instance);
    partial void UpdateCT_HD(CT_HD instance);
    partial void DeleteCT_HD(CT_HD instance);
    partial void InsertHOA_DON(HOA_DON instance);
    partial void UpdateHOA_DON(HOA_DON instance);
    partial void DeleteHOA_DON(HOA_DON instance);
    partial void InsertKHACH_HANG(KHACH_HANG instance);
    partial void UpdateKHACH_HANG(KHACH_HANG instance);
    partial void DeleteKHACH_HANG(KHACH_HANG instance);
    partial void InsertLoai_SP(Loai_SP instance);
    partial void UpdateLoai_SP(Loai_SP instance);
    partial void DeleteLoai_SP(Loai_SP instance);
    partial void InsertNHAN_VIEN(NHAN_VIEN instance);
    partial void UpdateNHAN_VIEN(NHAN_VIEN instance);
    partial void DeleteNHAN_VIEN(NHAN_VIEN instance);
    partial void InsertPhanLoai(PhanLoai instance);
    partial void UpdatePhanLoai(PhanLoai instance);
    partial void DeletePhanLoai(PhanLoai instance);
    partial void InsertSAN_PHAM(SAN_PHAM instance);
    partial void UpdateSAN_PHAM(SAN_PHAM instance);
    partial void DeleteSAN_PHAM(SAN_PHAM instance);
    partial void InsertTAI_KHOAN(TAI_KHOAN instance);
    partial void UpdateTAI_KHOAN(TAI_KHOAN instance);
    partial void DeleteTAI_KHOAN(TAI_KHOAN instance);
    partial void InsertTHUONG_HIEU(THUONG_HIEU instance);
    partial void UpdateTHUONG_HIEU(THUONG_HIEU instance);
    partial void DeleteTHUONG_HIEU(THUONG_HIEU instance);
    #endregion
		
		public dbSanPhamDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VzWebfinalversConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbSanPhamDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSanPhamDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSanPhamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSanPhamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cart> carts
		{
			get
			{
				return this.GetTable<cart>();
			}
		}
		
		public System.Data.Linq.Table<CHUC_VU> CHUC_VUs
		{
			get
			{
				return this.GetTable<CHUC_VU>();
			}
		}
		
		public System.Data.Linq.Table<CT_HD> CT_HDs
		{
			get
			{
				return this.GetTable<CT_HD>();
			}
		}
		
		public System.Data.Linq.Table<HOA_DON> HOA_DONs
		{
			get
			{
				return this.GetTable<HOA_DON>();
			}
		}
		
		public System.Data.Linq.Table<KHACH_HANG> KHACH_HANGs
		{
			get
			{
				return this.GetTable<KHACH_HANG>();
			}
		}
		
		public System.Data.Linq.Table<Loai_SP> Loai_SPs
		{
			get
			{
				return this.GetTable<Loai_SP>();
			}
		}
		
		public System.Data.Linq.Table<NHAN_VIEN> NHAN_VIENs
		{
			get
			{
				return this.GetTable<NHAN_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<PhanLoai> PhanLoais
		{
			get
			{
				return this.GetTable<PhanLoai>();
			}
		}
		
		public System.Data.Linq.Table<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this.GetTable<SAN_PHAM>();
			}
		}
		
		public System.Data.Linq.Table<TAI_KHOAN> TAI_KHOANs
		{
			get
			{
				return this.GetTable<TAI_KHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THUONG_HIEU> THUONG_HIEUs
		{
			get
			{
				return this.GetTable<THUONG_HIEU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cart")]
	public partial class cart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private System.Nullable<int> _SoluongMua;
		
		private string _MaKH;
		
		private System.Nullable<decimal> _Gia;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
		private EntityRef<SAN_PHAM> _SAN_PHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnSoluongMuaChanging(System.Nullable<int> value);
    partial void OnSoluongMuaChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    #endregion
		
		public cart()
		{
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			this._SAN_PHAM = default(EntityRef<SAN_PHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._SAN_PHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoluongMua", DbType="Int")]
		public System.Nullable<int> SoluongMua
		{
			get
			{
				return this._SoluongMua;
			}
			set
			{
				if ((this._SoluongMua != value))
				{
					this.OnSoluongMuaChanging(value);
					this.SendPropertyChanging();
					this._SoluongMua = value;
					this.SendPropertyChanged("SoluongMua");
					this.OnSoluongMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_cart", Storage="_KHACH_HANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.carts.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.carts.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_cart", Storage="_SAN_PHAM", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public SAN_PHAM SAN_PHAM
		{
			get
			{
				return this._SAN_PHAM.Entity;
			}
			set
			{
				SAN_PHAM previousValue = this._SAN_PHAM.Entity;
				if (((previousValue != value) 
							|| (this._SAN_PHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN_PHAM.Entity = null;
						previousValue.carts.Remove(this);
					}
					this._SAN_PHAM.Entity = value;
					if ((value != null))
					{
						value.carts.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(string);
					}
					this.SendPropertyChanged("SAN_PHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUC_VU")]
	public partial class CHUC_VU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCV;
		
		private string _ChucVu;
		
		private EntitySet<NHAN_VIEN> _NHAN_VIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public CHUC_VU()
		{
			this._NHAN_VIENs = new EntitySet<NHAN_VIEN>(new Action<NHAN_VIEN>(this.attach_NHAN_VIENs), new Action<NHAN_VIEN>(this.detach_NHAN_VIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(20)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUC_VU_NHAN_VIEN", Storage="_NHAN_VIENs", ThisKey="MaCV", OtherKey="MaCV")]
		public EntitySet<NHAN_VIEN> NHAN_VIENs
		{
			get
			{
				return this._NHAN_VIENs;
			}
			set
			{
				this._NHAN_VIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHAN_VIENs(NHAN_VIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUC_VU = this;
		}
		
		private void detach_NHAN_VIENs(NHAN_VIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUC_VU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_HD")]
	public partial class CT_HD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHÐ;
		
		private string _MaSP;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _TongGia;
		
		private string _NgayMua;
		
		private EntityRef<HOA_DON> _HOA_DON;
		
		private EntityRef<SAN_PHAM> _SAN_PHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHÐChanging(int value);
    partial void OnMaHÐChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnTongGiaChanging(System.Nullable<decimal> value);
    partial void OnTongGiaChanged();
    partial void OnNgayMuaChanging(string value);
    partial void OnNgayMuaChanged();
    #endregion
		
		public CT_HD()
		{
			this._HOA_DON = default(EntityRef<HOA_DON>);
			this._SAN_PHAM = default(EntityRef<SAN_PHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHÐ", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHÐ
		{
			get
			{
				return this._MaHÐ;
			}
			set
			{
				if ((this._MaHÐ != value))
				{
					if (this._HOA_DON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHÐChanging(value);
					this.SendPropertyChanging();
					this._MaHÐ = value;
					this.SendPropertyChanged("MaHÐ");
					this.OnMaHÐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._SAN_PHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TongGia
		{
			get
			{
				return this._TongGia;
			}
			set
			{
				if ((this._TongGia != value))
				{
					this.OnTongGiaChanging(value);
					this.SendPropertyChanging();
					this._TongGia = value;
					this.SendPropertyChanged("TongGia");
					this.OnTongGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMua", DbType="NVarChar(50)")]
		public string NgayMua
		{
			get
			{
				return this._NgayMua;
			}
			set
			{
				if ((this._NgayMua != value))
				{
					this.OnNgayMuaChanging(value);
					this.SendPropertyChanging();
					this._NgayMua = value;
					this.SendPropertyChanged("NgayMua");
					this.OnNgayMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOA_DON_CT_HD", Storage="_HOA_DON", ThisKey="MaHÐ", OtherKey="MaHÐ", IsForeignKey=true)]
		public HOA_DON HOA_DON
		{
			get
			{
				return this._HOA_DON.Entity;
			}
			set
			{
				HOA_DON previousValue = this._HOA_DON.Entity;
				if (((previousValue != value) 
							|| (this._HOA_DON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOA_DON.Entity = null;
						previousValue.CT_HDs.Remove(this);
					}
					this._HOA_DON.Entity = value;
					if ((value != null))
					{
						value.CT_HDs.Add(this);
						this._MaHÐ = value.MaHÐ;
					}
					else
					{
						this._MaHÐ = default(int);
					}
					this.SendPropertyChanged("HOA_DON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_CT_HD", Storage="_SAN_PHAM", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public SAN_PHAM SAN_PHAM
		{
			get
			{
				return this._SAN_PHAM.Entity;
			}
			set
			{
				SAN_PHAM previousValue = this._SAN_PHAM.Entity;
				if (((previousValue != value) 
							|| (this._SAN_PHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN_PHAM.Entity = null;
						previousValue.CT_HDs.Remove(this);
					}
					this._SAN_PHAM.Entity = value;
					if ((value != null))
					{
						value.CT_HDs.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(string);
					}
					this.SendPropertyChanged("SAN_PHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOA_DON")]
	public partial class HOA_DON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHÐ;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.Nullable<System.DateTime> _NgayGiao;
		
		private string _MaNV;
		
		private System.Nullable<bool> _GiaoHang;
		
		private System.Nullable<bool> _ThanhToan;
		
		private string _MaKH;
		
		private System.Nullable<decimal> _TongTienTT;
		
		private EntitySet<CT_HD> _CT_HDs;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
		private EntityRef<NHAN_VIEN> _NHAN_VIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHÐChanging(int value);
    partial void OnMaHÐChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnNgayGiaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnGiaoHangChanging(System.Nullable<bool> value);
    partial void OnGiaoHangChanged();
    partial void OnThanhToanChanging(System.Nullable<bool> value);
    partial void OnThanhToanChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTongTienTTChanging(System.Nullable<decimal> value);
    partial void OnTongTienTTChanged();
    #endregion
		
		public HOA_DON()
		{
			this._CT_HDs = new EntitySet<CT_HD>(new Action<CT_HD>(this.attach_CT_HDs), new Action<CT_HD>(this.detach_CT_HDs));
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			this._NHAN_VIEN = default(EntityRef<NHAN_VIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHÐ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHÐ
		{
			get
			{
				return this._MaHÐ;
			}
			set
			{
				if ((this._MaHÐ != value))
				{
					this.OnMaHÐChanging(value);
					this.SendPropertyChanging();
					this._MaHÐ = value;
					this.SendPropertyChanged("MaHÐ");
					this.OnMaHÐChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiao
		{
			get
			{
				return this._NgayGiao;
			}
			set
			{
				if ((this._NgayGiao != value))
				{
					this.OnNgayGiaoChanging(value);
					this.SendPropertyChanging();
					this._NgayGiao = value;
					this.SendPropertyChanged("NgayGiao");
					this.OnNgayGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(50)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHAN_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaoHang", DbType="Bit")]
		public System.Nullable<bool> GiaoHang
		{
			get
			{
				return this._GiaoHang;
			}
			set
			{
				if ((this._GiaoHang != value))
				{
					this.OnGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._GiaoHang = value;
					this.SendPropertyChanged("GiaoHang");
					this.OnGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhToan", DbType="Bit")]
		public System.Nullable<bool> ThanhToan
		{
			get
			{
				return this._ThanhToan;
			}
			set
			{
				if ((this._ThanhToan != value))
				{
					this.OnThanhToanChanging(value);
					this.SendPropertyChanging();
					this._ThanhToan = value;
					this.SendPropertyChanged("ThanhToan");
					this.OnThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTienTT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TongTienTT
		{
			get
			{
				return this._TongTienTT;
			}
			set
			{
				if ((this._TongTienTT != value))
				{
					this.OnTongTienTTChanging(value);
					this.SendPropertyChanging();
					this._TongTienTT = value;
					this.SendPropertyChanged("TongTienTT");
					this.OnTongTienTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOA_DON_CT_HD", Storage="_CT_HDs", ThisKey="MaHÐ", OtherKey="MaHÐ")]
		public EntitySet<CT_HD> CT_HDs
		{
			get
			{
				return this._CT_HDs;
			}
			set
			{
				this._CT_HDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_HOA_DON", Storage="_KHACH_HANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.HOA_DONs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.HOA_DONs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHAN_VIEN_HOA_DON", Storage="_NHAN_VIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHAN_VIEN NHAN_VIEN
		{
			get
			{
				return this._NHAN_VIEN.Entity;
			}
			set
			{
				NHAN_VIEN previousValue = this._NHAN_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHAN_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHAN_VIEN.Entity = null;
						previousValue.HOA_DONs.Remove(this);
					}
					this._NHAN_VIEN.Entity = value;
					if ((value != null))
					{
						value.HOA_DONs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NHAN_VIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HDs(CT_HD entity)
		{
			this.SendPropertyChanging();
			entity.HOA_DON = this;
		}
		
		private void detach_CT_HDs(CT_HD entity)
		{
			this.SendPropertyChanging();
			entity.HOA_DON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH_HANG")]
	public partial class KHACH_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenDangNhapTK;
		
		private string _HoTenKH;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _Email;
		
		private EntitySet<cart> _carts;
		
		private EntitySet<HOA_DON> _HOA_DONs;
		
		private EntityRef<TAI_KHOAN> _TAI_KHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenDangNhapTKChanging(string value);
    partial void OnTenDangNhapTKChanged();
    partial void OnHoTenKHChanging(string value);
    partial void OnHoTenKHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public KHACH_HANG()
		{
			this._carts = new EntitySet<cart>(new Action<cart>(this.attach_carts), new Action<cart>(this.detach_carts));
			this._HOA_DONs = new EntitySet<HOA_DON>(new Action<HOA_DON>(this.attach_HOA_DONs), new Action<HOA_DON>(this.detach_HOA_DONs));
			this._TAI_KHOAN = default(EntityRef<TAI_KHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhapTK", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string TenDangNhapTK
		{
			get
			{
				return this._TenDangNhapTK;
			}
			set
			{
				if ((this._TenDangNhapTK != value))
				{
					if (this._TAI_KHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapTKChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhapTK = value;
					this.SendPropertyChanged("TenDangNhapTK");
					this.OnTenDangNhapTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenKH", DbType="NVarChar(50)")]
		public string HoTenKH
		{
			get
			{
				return this._HoTenKH;
			}
			set
			{
				if ((this._HoTenKH != value))
				{
					this.OnHoTenKHChanging(value);
					this.SendPropertyChanging();
					this._HoTenKH = value;
					this.SendPropertyChanged("HoTenKH");
					this.OnHoTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(250)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_cart", Storage="_carts", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<cart> carts
		{
			get
			{
				return this._carts;
			}
			set
			{
				this._carts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_HOA_DON", Storage="_HOA_DONs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HOA_DON> HOA_DONs
		{
			get
			{
				return this._HOA_DONs;
			}
			set
			{
				this._HOA_DONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_KHACH_HANG", Storage="_TAI_KHOAN", ThisKey="TenDangNhapTK", OtherKey="TenDangNhapTK", IsForeignKey=true)]
		public TAI_KHOAN TAI_KHOAN
		{
			get
			{
				return this._TAI_KHOAN.Entity;
			}
			set
			{
				TAI_KHOAN previousValue = this._TAI_KHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAI_KHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAI_KHOAN.Entity = null;
						previousValue.KHACH_HANGs.Remove(this);
					}
					this._TAI_KHOAN.Entity = value;
					if ((value != null))
					{
						value.KHACH_HANGs.Add(this);
						this._TenDangNhapTK = value.TenDangNhapTK;
					}
					else
					{
						this._TenDangNhapTK = default(string);
					}
					this.SendPropertyChanged("TAI_KHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carts(cart entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_carts(cart entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
		
		private void attach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loai_SP")]
	public partial class Loai_SP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_Loai;
		
		private string _TenLoai;
		
		private EntitySet<SAN_PHAM> _SAN_PHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_LoaiChanging(int value);
    partial void OnMa_LoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public Loai_SP()
		{
			this._SAN_PHAMs = new EntitySet<SAN_PHAM>(new Action<SAN_PHAM>(this.attach_SAN_PHAMs), new Action<SAN_PHAM>(this.detach_SAN_PHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Loai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_Loai
		{
			get
			{
				return this._Ma_Loai;
			}
			set
			{
				if ((this._Ma_Loai != value))
				{
					this.OnMa_LoaiChanging(value);
					this.SendPropertyChanging();
					this._Ma_Loai = value;
					this.SendPropertyChanged("Ma_Loai");
					this.OnMa_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_SP_SAN_PHAM", Storage="_SAN_PHAMs", ThisKey="Ma_Loai", OtherKey="Ma_Loai")]
		public EntitySet<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this._SAN_PHAMs;
			}
			set
			{
				this._SAN_PHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.Loai_SP = this;
		}
		
		private void detach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.Loai_SP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHAN_VIEN")]
	public partial class NHAN_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenDangNhapTK;
		
		private string _MaCV;
		
		private string _HoTen;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _Email;
		
		private EntitySet<HOA_DON> _HOA_DONs;
		
		private EntityRef<CHUC_VU> _CHUC_VU;
		
		private EntityRef<TAI_KHOAN> _TAI_KHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenDangNhapTKChanging(string value);
    partial void OnTenDangNhapTKChanged();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public NHAN_VIEN()
		{
			this._HOA_DONs = new EntitySet<HOA_DON>(new Action<HOA_DON>(this.attach_HOA_DONs), new Action<HOA_DON>(this.detach_HOA_DONs));
			this._CHUC_VU = default(EntityRef<CHUC_VU>);
			this._TAI_KHOAN = default(EntityRef<TAI_KHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhapTK", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string TenDangNhapTK
		{
			get
			{
				return this._TenDangNhapTK;
			}
			set
			{
				if ((this._TenDangNhapTK != value))
				{
					if (this._TAI_KHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapTKChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhapTK = value;
					this.SendPropertyChanged("TenDangNhapTK");
					this.OnTenDangNhapTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					if (this._CHUC_VU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(250)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(40)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHAN_VIEN_HOA_DON", Storage="_HOA_DONs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HOA_DON> HOA_DONs
		{
			get
			{
				return this._HOA_DONs;
			}
			set
			{
				this._HOA_DONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUC_VU_NHAN_VIEN", Storage="_CHUC_VU", ThisKey="MaCV", OtherKey="MaCV", IsForeignKey=true)]
		public CHUC_VU CHUC_VU
		{
			get
			{
				return this._CHUC_VU.Entity;
			}
			set
			{
				CHUC_VU previousValue = this._CHUC_VU.Entity;
				if (((previousValue != value) 
							|| (this._CHUC_VU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUC_VU.Entity = null;
						previousValue.NHAN_VIENs.Remove(this);
					}
					this._CHUC_VU.Entity = value;
					if ((value != null))
					{
						value.NHAN_VIENs.Add(this);
						this._MaCV = value.MaCV;
					}
					else
					{
						this._MaCV = default(string);
					}
					this.SendPropertyChanged("CHUC_VU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_NHAN_VIEN", Storage="_TAI_KHOAN", ThisKey="TenDangNhapTK", OtherKey="TenDangNhapTK", IsForeignKey=true)]
		public TAI_KHOAN TAI_KHOAN
		{
			get
			{
				return this._TAI_KHOAN.Entity;
			}
			set
			{
				TAI_KHOAN previousValue = this._TAI_KHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAI_KHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAI_KHOAN.Entity = null;
						previousValue.NHAN_VIENs.Remove(this);
					}
					this._TAI_KHOAN.Entity = value;
					if ((value != null))
					{
						value.NHAN_VIENs.Add(this);
						this._TenDangNhapTK = value.TenDangNhapTK;
					}
					else
					{
						this._TenDangNhapTK = default(string);
					}
					this.SendPropertyChanged("TAI_KHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.NHAN_VIEN = this;
		}
		
		private void detach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.NHAN_VIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanLoai")]
	public partial class PhanLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhanLoai;
		
		private string _TenPhanLoai;
		
		private EntitySet<SAN_PHAM> _SAN_PHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhanLoaiChanging(int value);
    partial void OnMaPhanLoaiChanged();
    partial void OnTenPhanLoaiChanging(string value);
    partial void OnTenPhanLoaiChanged();
    #endregion
		
		public PhanLoai()
		{
			this._SAN_PHAMs = new EntitySet<SAN_PHAM>(new Action<SAN_PHAM>(this.attach_SAN_PHAMs), new Action<SAN_PHAM>(this.detach_SAN_PHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhanLoai
		{
			get
			{
				return this._MaPhanLoai;
			}
			set
			{
				if ((this._MaPhanLoai != value))
				{
					this.OnMaPhanLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaPhanLoai = value;
					this.SendPropertyChanged("MaPhanLoai");
					this.OnMaPhanLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhanLoai", DbType="NVarChar(50)")]
		public string TenPhanLoai
		{
			get
			{
				return this._TenPhanLoai;
			}
			set
			{
				if ((this._TenPhanLoai != value))
				{
					this.OnTenPhanLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenPhanLoai = value;
					this.SendPropertyChanged("TenPhanLoai");
					this.OnTenPhanLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanLoai_SAN_PHAM", Storage="_SAN_PHAMs", ThisKey="MaPhanLoai", OtherKey="MaPhanLoai")]
		public EntitySet<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this._SAN_PHAMs;
			}
			set
			{
				this._SAN_PHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.PhanLoai = this;
		}
		
		private void detach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.PhanLoai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAN_PHAM")]
	public partial class SAN_PHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private int _Ma_Loai;
		
		private int _MaPhanLoai;
		
		private string _TenSP;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _Gia;
		
		private int _Ma_TH;
		
		private string _GioiThieuSP;
		
		private string _HinhAnhSP;
		
		private string _HinhAnhCT1;
		
		private string _HinhAnhCT2;
		
		private string _HinhAnhCT3;
		
		private string _HinhAnhCT4;
		
		private System.Nullable<int> _SLTruyCap;
		
		private EntitySet<cart> _carts;
		
		private EntitySet<CT_HD> _CT_HDs;
		
		private EntityRef<Loai_SP> _Loai_SP;
		
		private EntityRef<PhanLoai> _PhanLoai;
		
		private EntityRef<THUONG_HIEU> _THUONG_HIEU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnMa_LoaiChanging(int value);
    partial void OnMa_LoaiChanged();
    partial void OnMaPhanLoaiChanging(int value);
    partial void OnMaPhanLoaiChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnMa_THChanging(int value);
    partial void OnMa_THChanged();
    partial void OnGioiThieuSPChanging(string value);
    partial void OnGioiThieuSPChanged();
    partial void OnHinhAnhSPChanging(string value);
    partial void OnHinhAnhSPChanged();
    partial void OnHinhAnhCT1Changing(string value);
    partial void OnHinhAnhCT1Changed();
    partial void OnHinhAnhCT2Changing(string value);
    partial void OnHinhAnhCT2Changed();
    partial void OnHinhAnhCT3Changing(string value);
    partial void OnHinhAnhCT3Changed();
    partial void OnHinhAnhCT4Changing(string value);
    partial void OnHinhAnhCT4Changed();
    partial void OnSLTruyCapChanging(System.Nullable<int> value);
    partial void OnSLTruyCapChanged();
    #endregion
		
		public SAN_PHAM()
		{
			this._carts = new EntitySet<cart>(new Action<cart>(this.attach_carts), new Action<cart>(this.detach_carts));
			this._CT_HDs = new EntitySet<CT_HD>(new Action<CT_HD>(this.attach_CT_HDs), new Action<CT_HD>(this.detach_CT_HDs));
			this._Loai_SP = default(EntityRef<Loai_SP>);
			this._PhanLoai = default(EntityRef<PhanLoai>);
			this._THUONG_HIEU = default(EntityRef<THUONG_HIEU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Loai", DbType="Int NOT NULL")]
		public int Ma_Loai
		{
			get
			{
				return this._Ma_Loai;
			}
			set
			{
				if ((this._Ma_Loai != value))
				{
					if (this._Loai_SP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_LoaiChanging(value);
					this.SendPropertyChanging();
					this._Ma_Loai = value;
					this.SendPropertyChanged("Ma_Loai");
					this.OnMa_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanLoai", DbType="Int NOT NULL")]
		public int MaPhanLoai
		{
			get
			{
				return this._MaPhanLoai;
			}
			set
			{
				if ((this._MaPhanLoai != value))
				{
					if (this._PhanLoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhanLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaPhanLoai = value;
					this.SendPropertyChanged("MaPhanLoai");
					this.OnMaPhanLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(70)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_TH", DbType="Int NOT NULL")]
		public int Ma_TH
		{
			get
			{
				return this._Ma_TH;
			}
			set
			{
				if ((this._Ma_TH != value))
				{
					if (this._THUONG_HIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_THChanging(value);
					this.SendPropertyChanging();
					this._Ma_TH = value;
					this.SendPropertyChanged("Ma_TH");
					this.OnMa_THChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieuSP", DbType="NVarChar(500)")]
		public string GioiThieuSP
		{
			get
			{
				return this._GioiThieuSP;
			}
			set
			{
				if ((this._GioiThieuSP != value))
				{
					this.OnGioiThieuSPChanging(value);
					this.SendPropertyChanging();
					this._GioiThieuSP = value;
					this.SendPropertyChanged("GioiThieuSP");
					this.OnGioiThieuSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhSP", DbType="NVarChar(200)")]
		public string HinhAnhSP
		{
			get
			{
				return this._HinhAnhSP;
			}
			set
			{
				if ((this._HinhAnhSP != value))
				{
					this.OnHinhAnhSPChanging(value);
					this.SendPropertyChanging();
					this._HinhAnhSP = value;
					this.SendPropertyChanged("HinhAnhSP");
					this.OnHinhAnhSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhCT1", DbType="NVarChar(200)")]
		public string HinhAnhCT1
		{
			get
			{
				return this._HinhAnhCT1;
			}
			set
			{
				if ((this._HinhAnhCT1 != value))
				{
					this.OnHinhAnhCT1Changing(value);
					this.SendPropertyChanging();
					this._HinhAnhCT1 = value;
					this.SendPropertyChanged("HinhAnhCT1");
					this.OnHinhAnhCT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhCT2", DbType="NVarChar(200)")]
		public string HinhAnhCT2
		{
			get
			{
				return this._HinhAnhCT2;
			}
			set
			{
				if ((this._HinhAnhCT2 != value))
				{
					this.OnHinhAnhCT2Changing(value);
					this.SendPropertyChanging();
					this._HinhAnhCT2 = value;
					this.SendPropertyChanged("HinhAnhCT2");
					this.OnHinhAnhCT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhCT3", DbType="NVarChar(200)")]
		public string HinhAnhCT3
		{
			get
			{
				return this._HinhAnhCT3;
			}
			set
			{
				if ((this._HinhAnhCT3 != value))
				{
					this.OnHinhAnhCT3Changing(value);
					this.SendPropertyChanging();
					this._HinhAnhCT3 = value;
					this.SendPropertyChanged("HinhAnhCT3");
					this.OnHinhAnhCT3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhCT4", DbType="NVarChar(200)")]
		public string HinhAnhCT4
		{
			get
			{
				return this._HinhAnhCT4;
			}
			set
			{
				if ((this._HinhAnhCT4 != value))
				{
					this.OnHinhAnhCT4Changing(value);
					this.SendPropertyChanging();
					this._HinhAnhCT4 = value;
					this.SendPropertyChanged("HinhAnhCT4");
					this.OnHinhAnhCT4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLTruyCap", DbType="Int")]
		public System.Nullable<int> SLTruyCap
		{
			get
			{
				return this._SLTruyCap;
			}
			set
			{
				if ((this._SLTruyCap != value))
				{
					this.OnSLTruyCapChanging(value);
					this.SendPropertyChanging();
					this._SLTruyCap = value;
					this.SendPropertyChanged("SLTruyCap");
					this.OnSLTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_cart", Storage="_carts", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<cart> carts
		{
			get
			{
				return this._carts;
			}
			set
			{
				this._carts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_CT_HD", Storage="_CT_HDs", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<CT_HD> CT_HDs
		{
			get
			{
				return this._CT_HDs;
			}
			set
			{
				this._CT_HDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_SP_SAN_PHAM", Storage="_Loai_SP", ThisKey="Ma_Loai", OtherKey="Ma_Loai", IsForeignKey=true)]
		public Loai_SP Loai_SP
		{
			get
			{
				return this._Loai_SP.Entity;
			}
			set
			{
				Loai_SP previousValue = this._Loai_SP.Entity;
				if (((previousValue != value) 
							|| (this._Loai_SP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Loai_SP.Entity = null;
						previousValue.SAN_PHAMs.Remove(this);
					}
					this._Loai_SP.Entity = value;
					if ((value != null))
					{
						value.SAN_PHAMs.Add(this);
						this._Ma_Loai = value.Ma_Loai;
					}
					else
					{
						this._Ma_Loai = default(int);
					}
					this.SendPropertyChanged("Loai_SP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanLoai_SAN_PHAM", Storage="_PhanLoai", ThisKey="MaPhanLoai", OtherKey="MaPhanLoai", IsForeignKey=true)]
		public PhanLoai PhanLoai
		{
			get
			{
				return this._PhanLoai.Entity;
			}
			set
			{
				PhanLoai previousValue = this._PhanLoai.Entity;
				if (((previousValue != value) 
							|| (this._PhanLoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanLoai.Entity = null;
						previousValue.SAN_PHAMs.Remove(this);
					}
					this._PhanLoai.Entity = value;
					if ((value != null))
					{
						value.SAN_PHAMs.Add(this);
						this._MaPhanLoai = value.MaPhanLoai;
					}
					else
					{
						this._MaPhanLoai = default(int);
					}
					this.SendPropertyChanged("PhanLoai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONG_HIEU_SAN_PHAM", Storage="_THUONG_HIEU", ThisKey="Ma_TH", OtherKey="Ma_TH", IsForeignKey=true)]
		public THUONG_HIEU THUONG_HIEU
		{
			get
			{
				return this._THUONG_HIEU.Entity;
			}
			set
			{
				THUONG_HIEU previousValue = this._THUONG_HIEU.Entity;
				if (((previousValue != value) 
							|| (this._THUONG_HIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUONG_HIEU.Entity = null;
						previousValue.SAN_PHAMs.Remove(this);
					}
					this._THUONG_HIEU.Entity = value;
					if ((value != null))
					{
						value.SAN_PHAMs.Add(this);
						this._Ma_TH = value.Ma_TH;
					}
					else
					{
						this._Ma_TH = default(int);
					}
					this.SendPropertyChanged("THUONG_HIEU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carts(cart entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = this;
		}
		
		private void detach_carts(cart entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = null;
		}
		
		private void attach_CT_HDs(CT_HD entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = this;
		}
		
		private void detach_CT_HDs(CT_HD entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAI_KHOAN")]
	public partial class TAI_KHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhapTK;
		
		private string _MatKhau;
		
		private EntitySet<KHACH_HANG> _KHACH_HANGs;
		
		private EntitySet<NHAN_VIEN> _NHAN_VIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapTKChanging(string value);
    partial void OnTenDangNhapTKChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public TAI_KHOAN()
		{
			this._KHACH_HANGs = new EntitySet<KHACH_HANG>(new Action<KHACH_HANG>(this.attach_KHACH_HANGs), new Action<KHACH_HANG>(this.detach_KHACH_HANGs));
			this._NHAN_VIENs = new EntitySet<NHAN_VIEN>(new Action<NHAN_VIEN>(this.attach_NHAN_VIENs), new Action<NHAN_VIEN>(this.detach_NHAN_VIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhapTK", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhapTK
		{
			get
			{
				return this._TenDangNhapTK;
			}
			set
			{
				if ((this._TenDangNhapTK != value))
				{
					this.OnTenDangNhapTKChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhapTK = value;
					this.SendPropertyChanged("TenDangNhapTK");
					this.OnTenDangNhapTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_KHACH_HANG", Storage="_KHACH_HANGs", ThisKey="TenDangNhapTK", OtherKey="TenDangNhapTK")]
		public EntitySet<KHACH_HANG> KHACH_HANGs
		{
			get
			{
				return this._KHACH_HANGs;
			}
			set
			{
				this._KHACH_HANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_NHAN_VIEN", Storage="_NHAN_VIENs", ThisKey="TenDangNhapTK", OtherKey="TenDangNhapTK")]
		public EntitySet<NHAN_VIEN> NHAN_VIENs
		{
			get
			{
				return this._NHAN_VIENs;
			}
			set
			{
				this._NHAN_VIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACH_HANGs(KHACH_HANG entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = this;
		}
		
		private void detach_KHACH_HANGs(KHACH_HANG entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = null;
		}
		
		private void attach_NHAN_VIENs(NHAN_VIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = this;
		}
		
		private void detach_NHAN_VIENs(NHAN_VIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUONG_HIEU")]
	public partial class THUONG_HIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_TH;
		
		private string _TenTH;
		
		private EntitySet<SAN_PHAM> _SAN_PHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_THChanging(int value);
    partial void OnMa_THChanged();
    partial void OnTenTHChanging(string value);
    partial void OnTenTHChanged();
    #endregion
		
		public THUONG_HIEU()
		{
			this._SAN_PHAMs = new EntitySet<SAN_PHAM>(new Action<SAN_PHAM>(this.attach_SAN_PHAMs), new Action<SAN_PHAM>(this.detach_SAN_PHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_TH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_TH
		{
			get
			{
				return this._Ma_TH;
			}
			set
			{
				if ((this._Ma_TH != value))
				{
					this.OnMa_THChanging(value);
					this.SendPropertyChanging();
					this._Ma_TH = value;
					this.SendPropertyChanged("Ma_TH");
					this.OnMa_THChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTH", DbType="NVarChar(250)")]
		public string TenTH
		{
			get
			{
				return this._TenTH;
			}
			set
			{
				if ((this._TenTH != value))
				{
					this.OnTenTHChanging(value);
					this.SendPropertyChanging();
					this._TenTH = value;
					this.SendPropertyChanged("TenTH");
					this.OnTenTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONG_HIEU_SAN_PHAM", Storage="_SAN_PHAMs", ThisKey="Ma_TH", OtherKey="Ma_TH")]
		public EntitySet<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this._SAN_PHAMs;
			}
			set
			{
				this._SAN_PHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.THUONG_HIEU = this;
		}
		
		private void detach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.THUONG_HIEU = null;
		}
	}
}
#pragma warning restore 1591
